### PR TITLE
Feature/support laravel7

### PR DESCRIPTION
**Pull request by jimmypuckett**

### CODE REVIEW

**Comment by ssfinney** [comment]
@jimmypuckett Build is failing

**Comment by hugo-lovighi** [comment]
@jimmypuckett any idea ?

**Comment by jimmypuckett** [comment]
Fixing now.  Sorry for the delay.  I just pushed an update.  As soon as test pass, then I will merge & tag.

**Comment by jimmypuckett** [comment]
@ssfinney This appears to be hung on the test.  Do you seen anything wrong?

**Comment by jimmypuckett** [comment]
@kesm0, we will be tagging a new version in just a bit.

**Pull request merged**
